FROM python:3.10-slim

WORKDIR /app

# 安裝 libgomp1
RUN apt-get update && apt-get install -y libgomp1

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

EXPOSE 8501

CMD ["streamlit", "run", "src/app.py", "--server.port=8501", "--server.address=0.0.0.0"]